### PR TITLE
Add missed mysqlClustersGlobalServiceMonitor

### LINKED ISSUE #804: mysqlClustersGlobalServiceMonitor.enabled: true ,but it not used everywhere

### PR DESCRIPTION
**Pull request by w33dw0r7d**
closes/fixes #804

---
 - [v] I've made sure the [Changelog.md](https://github.com/presslabs/mysql-operator/blob/master/Changelog.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

**Comment by w33dw0r7d** [comment]
@cndoit18  please review

**Review by cndoit18 — COMMENTED** [review]
Hi, thank you very much for your contribution. 

I have a question, what is the difference between `mysqlClustersGlobalServiceMonitor` and `serviceMonitor`, and if there is no difference between the two, is it enough to save `serviceMonitor`?

**Comment by w33dw0r7d** [comment]
serviceMonitor - to monitor operator itself
mysqlClustersGlobalServiceMonitor - to monitor mysqlCluster instances

**Comment by cndoit18** [comment]
> serviceMonitor - to monitor operator itself mysqlClustersGlobalServiceMonitor - to monitor mysqlCluster instances

got it 👍

**Review by cndoit18 — APPROVED** [review]
LGTM

**Comment by w33dw0r7d** [comment]
Test failed. It isn’t  my changes.

**Pull request merged**
