### PR TITLE
Add optional field to keep pvc after cluster been deleted

### PR DESCRIPTION
**Pull request by drivebyer**
closes/fixes https://github.com/bitpoke/mysql-operator/issues/892

---
 - [x] I've made sure the [CHANGELOG.md](https://github.com/presslabs/mysql-operator/blob/master/CHANGELOG.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

**Comment by drivebyer** [comment]
PTAL @cndoit18

**Review by cndoit18 — APPROVED** [review]

**Comment by drivebyer** [comment]
ready to merge plz @cndoit18

**Comment by Littlehhao** [comment]
when will it be released

**Comment by drivebyer** [comment]
> when will it be released

hard to say, you can packge on yourself.

**Comment by Littlehhao** [comment]
I see that docker.io already supports bitpoke/mysql-operator:v0.6.3
version of the mirror. I don’t know if this version of the image fixes this bug.

**Comment by drivebyer** [comment]
> I don’t know if this version of the image fixes this bug.

No, v0.6.3 only contains these commit https://github.com/bitpoke/mysql-operator/commits/v0.6.3

**Comment by drivebyer** [comment]
> I don’t know if this version of the image fixes this bug.

No, v0.6.3 only contains these commit https://github.com/bitpoke/mysql-operator/commits/v0.6.3

**Comment by Littlehhao** [comment]
What about version 0.7.0-amd64?

**Comment by Littlehhao** [comment]
https://hub.docker.com/layers/bitpoke/mysql-operator-orchestrator/0.7.0-amd64/images/sha256-724546e6c7a788a65c9d420e671087036e36c7fbe31d6b0f9b33c930839427b0?context=explore

**Comment by drivebyer** [comment]
> What about version 0.7.0-amd64?

maybe not, it pushed 5 months ago

**Comment by Littlehhao** [comment]
I didn't build successfully. Can you help me build this image?

**Comment by drivebyer** [comment]
you could post an issue, asking the community for help.

**Comment by Littlehhao** [comment]
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load

When I executed the make command, the built image was not found. The prompt does not specify the -t parameter. How should I execute the command and build the image?

image

**Comment by Littlehhao** [comment]
@drivebyer I want to seek your answer

**Comment by Littlehhao** [comment]
I added keepAfterDelete to both mysql-cluster and crd files. 
image
image


But when I start the mysql-operator cluster, I get an error

image
@drivebyer

**Comment by drivebyer** [comment]
try 'keepAfterDelete', not KeepAfterDelete @Littlehhao

**Comment by Littlehhao** [comment]
Thank you very much, I made it

**Comment by Littlehhao** [comment]
Do you know how to build the arm64 package?
@drivebyer

**Pull request merged**
