### PR TITLE
fix: dsn will always not be check with expectedDSN

### PR DESCRIPTION
**Pull request by drivebyer**
closes/fixes #xyz

---
 - [x] I've made sure the [CHANGELOG.md](https://github.com/presslabs/mysql-operator/blob/master/CHANGELOG.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

**Comment by drivebyer** [comment]
PTAL @cndoit18

**Review by cndoit18 — CHANGES_REQUESTED** [review]
Why not add an `AssertExpectedDSN`

**Comment by drivebyer** [comment]
> Why not add an `AssertExpectedDSN`

I think the right sentence is "assert dsn with expected dsn", so maybe `AssertDSN` is better :)

If we need a more semantic method name,  maybe `AddExpectedDSN` is better, just like:
https://github.com/bitpoke/mysql-operator/blob/42e15e6da8e0b83114c03f41a4a0b668a162d204/pkg/controller/mysqluser/mysqluser_controller_test.go#L266-L267

**Review by cndoit18 — APPROVED** [review]
LGTM

**Pull request merged**
