### PR TITLE
Make sure orchestrator can find the templates

### LINKED ISSUE #741: "templates/layout" is undefined after upgrade to v0.5.1
I upgraded mysql-operator from 0.4.0 to 0.5.1. Now, when accessing the orchestrator web UI, I get redirected to `/web/clusters` where I obtain a response with status code 500 and payload:

```
html/template: "templates/layout" is undefined
```

### PR DESCRIPTION
**Pull request by abh**
fixes #741

### CODE REVIEW

**Review by cndoit18 — APPROVED** [review]
LGTM

**Comment by calind** [comment]
A better place to fix this is in https://github.com/bitpoke/mysql-operator/blob/master/images/mysql-operator-orchestrator/Dockerfile by setting the WORKDIR there.

**Review by calind — CHANGES_REQUESTED** [review]
A better place to fix this is in https://github.com/bitpoke/mysql-operator/blob/master/images/mysql-operator-orchestrator/Dockerfile by setting the WORKDIR there. This way we fix non-helm installs as well.

**Comment by calind** [comment]
Fixed in https://github.com/bitpoke/mysql-operator/commit/9a48e0660f646c23a4db9e7f70f655ece2695a4c.

**Pull request closed without merging**
