### PR TITLE
Limit backup job name to 63 chars, fix #836

### LINKED ISSUE #836: Limit backup job name to 63 charts
This issue is like #577. 

`Warning  JobSyncFailed  9m21s (x163 over 39h)  mysqlbackup-controller  batch/v1, Kind=Job keycloak/keycloak-mysql-mysql-cluster-im-db-auto-2022-08-05t00-00-00-backup failed syncing: Job.batch "keycloak-mysql-mysql-cluster-im-db-auto-2022-08-05t00-00-00-backup" is invalid: spec.template.labels: Invalid value: "keycloak-mysql-mysql-cluster-im-db-auto-2022-08-05t00-00-00-backup": must be no more than 63 characters`

### PR DESCRIPTION
**Pull request by w33dw0r7d**
closes/fixes #836

### CODE REVIEW

**Comment by w33dw0r7d** [comment]
@cndoit18 review please.

**Review by cndoit18 — COMMENTED** [review]
Thank you very much for your contribution, add some unit tests, plz.

**Comment by w33dw0r7d** [comment]
@cndoit18 Thank you for review. Add tests.

**Comment by w33dw0r7d** [comment]
@cndoit18 review please.

**Review by cndoit18 — APPROVED** [review]

**Comment by w33dw0r7d** [comment]
@cndoit18 Merge please.

**Comment by cndoit18** [comment]
Hi, squash your commits, plz

**Pull request merged**
