### PR TITLE
[bugfix]update node_controller.go

### PR DESCRIPTION
**Pull request by jiuker**
Reproduction steps:
1. Start mysql-operator.
2. Start the mysql instance.
3. Wait for all mysql instances to run successfully.
4. Close mysql-operator (to simulate network failure, node down, etc.).
5. Restart the node containing the mysql instance(Machine reboot).
6. The mysql instances on these nodes will start automatically, but since init will set configfure to 0.
7. Wait for all these nodes to stop changing.
8. Start mysql-operator, which will not automatically repair the current cluster because it is listening to the updated pod.
9. and the mysql cluster is in an unhealthy state due to configfure=0.

closes/fixes #xyz

---
 - [x] I've made sure the [CHANGELOG.md](https://github.com/presslabs/mysql-operator/blob/master/CHANGELOG.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

**Comment by jiuker** [comment]
@cndoit18

**Review by cndoit18 — APPROVED** [review]

**Comment by jiuker** [comment]
img

operator will do noting @cndoit18

**Comment by jiuker** [comment]
@cndoit18

**Review by cndoit18 — APPROVED** [review]

**Comment by jiuker** [comment]
@cndoit18 I have done changelings.

**Review by cndoit18 — APPROVED** [review]

**Comment by jiuker** [comment]
@cndoit18 any suggestion？

**Comment by jiuker** [comment]
@cndoit18 
@milero

**Comment by zgfh** [comment]
@cndoit18
@milero
PTAL

**Comment by panpan0000** [comment]
does it fix this issue https://github.com/bitpoke/mysql-operator/issues/416 ?

**Comment by odoucet** [comment]
> does it fix this issue #416 ?

We are using bitpoke operator 0.6.3 and encountered bug #416 today, so no, it does not fix the issue.

**Pull request merged**
